name: Deployment pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - run: npm test
      - run: npm run build
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
  deploy:
    runs-on: ubuntu-latest
    needs: [ build_and_test ]
    steps:
      - name: Trigger deployment
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
        if: ${{ github.event_name == 'push' && (!contains(join(github.event.commits.*.message, ''), '#skip'))}}

  notify_failure:
    runs-on: ubuntu-latest
    needs: [ deploy, build_and_test ]
    if: ${{ !success() }}
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: ${{ github.event_name == 'push' && (!contains(join(github.event.commits.*.message, ''), '#skip'))}}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: Fullstack part 11 Hook
          url: https://github.com/EljasV/Fullstack-CI
          description: |
            ${{ format('Hash: {0}', github.sha) }}

  notify_success:
    needs: [ deploy ]
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: ${{ github.event_name == 'push' && (!contains(join(github.event.commits.*.message, ''), '#skip'))}}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nocontext: true
          username: Fullstack part 11 Hook
          url: https://github.com/EljasV/Fullstack-CI
          description: |
            ${{ format('Hash: {0}', github.sha) }}
  

  tag_release:
    needs: [ deploy ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        if: ${{ github.event_name == 'push' && (!contains(join(github.event.commits.*.message, ''), '#skip'))}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
